### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by ryankbales** [paperdigits/middleman-foundation-6#1]
I have a `middleman` directory.  Inside that directory I clone this repo: `git clone git://github.com/paperdigits/middleman-foundation-6.git .middleman/middleman-foundation-6`

Per instructions I run `middleman init mygithubacct.github.io --template=.middleman/middleman-foundation-6`  (I will be setting up for Github pages, hence the repo name.)

This is what is returned:

```
run  git clone --depth 1 git://github.com/.middleman/middleman-foundation-6.git /var/folders/r0/rv_dq4qn1y50b_l8btyrz6z40000gn/T/d20160103-59217-fp30y4 from "."
Cloning into '/var/folders/r0/rv_dq4qn1y50b_l8btyrz6z40000gn/T/d20160103-59217-fp30y4'...
fatal: remote error:
  Repository not found.
Git clone failed, maybe the url is invalid or you don't have the permissions?
```

I have tried cloning this in my `~` directory and get the same results.  What am I missing?  Thanks.

**Comment by ryankbales** [comment]
This appears to me a Middleman issue on my local machine or with `middleman`.  I'll close out.

**Comment by ryankbales** [comment]
Looks like the .middleman/ dir is no longer.... https://middlemanapp.com/basics/upgrade-v4/#installing-templates-from-git

**Comment by ryankbales** [comment]
Found the new method here: https://middlemanapp.com/basics/upgrade-v4/#installing-templates-from-git

Since I am using v4, they had an upgrade how to clone methods.

`middleman init -T https://github.com/paperdigits/middleman-foundation-6 my-new-project`

**Comment by paperdigits** [comment]
@ryankbales Sorry I've been a bit busy lately; I'm glad you were able to solve the problem. I built and tested this using Middleman 3.x.
