### ISSUE TITLE
settings.scss missing

### ISSUE THREAD

**Issue by adedip** [paperdigits/middleman-foundation-6#6]
I can't find the settings.scss to override foundation configurations.

i.e. I can't find where to change $total-columns to 24.

Thanks!

**Comment by paperdigits** [comment]
There isn't a copy of Foundation in this project, so I didn't want to keep a copy of `_settings.scss`, as you'd be liable to have an out of date version when you fetch Foundation using Bower. `_settings.scss` isn't distributed with Foundation either, you need to fetch it if you want to make changes; see the documentation [on the Foundation site.](http://foundation.zurb.com/sites/docs/sass.html)

You can fetch the latest `_settings.scss` [here](https://raw.githubusercontent.com/zurb/foundation-sites/master/scss/settings/_settings.scss), but make sure you have the latest version of Foundation from Bower as well, or you're liable for a miss-match.

I'll update the documentation as well.

**Comment by adedip** [comment]
@paperdigits thank you! that's pretty clear ;)

**Comment by paperdigits** [comment]
Documentation updated in 4b819a5236af8b440fad975f995828f76e217072 and 250e63d614441b2ac61dca6721a53517fa9e7232
